// <auto-generated />
using Bobbins.Comments.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Bobbins.Comments.Migrate.Migrations
{
    [DbContext(typeof(CommentContext))]
    [Migration("20171112005036_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Bobbins.Comments.Data.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<int>("DownVoteCount");

                    b.Property<int>("LinkId");

                    b.Property<int>("ReplyCount");

                    b.Property<int?>("ReplyToId");

                    b.Property<string>("Text");

                    b.Property<int>("UpVoteCount");

                    b.Property<string>("User")
                        .HasMaxLength(16);

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Bobbins.Comments.Data.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CommentId");

                    b.Property<string>("User")
                        .HasMaxLength(16);

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CommentId", "User")
                        .IsUnique();

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("Bobbins.Comments.Data.Vote", b =>
                {
                    b.HasOne("Bobbins.Comments.Data.Comment", "Comment")
                        .WithMany("Votes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
